return {
    -- "folke/snacks.nvim",
    -- lazy = false,
    -- -- Configure only what you need:
    -- -- Set up handy keybindings to invoke various snacks pickers:
    -- opts = {
    --     picker = {
    --         enabled = true,
    --         layout = {
    --             preset = "ivy",
    --         },
    --     },
    -- },
    -- -- config = function()
    -- --     -- You can't use config and opts together, config takes precident
    -- --     require("snacks").setup(opts)
    -- --     vim.api.nvim_set_hl(0, "SnacksPicker", { bg = "NONE" })
    -- -- end,
    -- keys = {
    --     { "<leader>sf", function() Snacks.picker.files() end,   desc = "Find Files" },
    --     {
    --         "<leader>sF",
    --         function()
    --             Snacks.picker.files({ cwd = vim.fn.expand("%:p:h") })
    --         end,
    --         desc = "Find Files from current file's directory"
    --     },
    --     { "<leader>sr", function() Snacks.picker.recent() end,  desc = "Recent Files" },
    --     { "<leader>sb", function() Snacks.picker.buffers() end, desc = "Buffers" },
    --     { "<leader>sg", function() Snacks.picker.grep() end,    desc = "Grep (Ripgrep)" },
    --     {
    --         "<leader>sG",
    --         function()
    --             Snacks.picker.grep({ cwd = vim.fn.expand("%:p:h") })
    --         end,
    --         desc = "Grep from current file's directory"
    --     },
    --
    --     { "<leader>sh", function() Snacks.picker.command_history() end, desc = "Cmd History" },
    --     { "<leader>sn", function() Snacks.picker.notifications() end,   desc = "Notifications" },
    --     { "<leader>gd", function() Snacks.picker.git_diff() end,        desc = "Git Diff (Hunks)" },
    --     { "<leader>gs", function() Snacks.picker.git_status() end,      desc = "Git Status" },
    --     { "<leader>gb", function() Snacks.picker.git_branches() end,    desc = "Git Branches" },
    -- },
}
