- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    user: "{{lookup('env', 'USER') }}"
    home: "/home/{{ user }}"
    dotfiles_dir: "{{ home }}/dotfiles"
  tasks:

    - name: Install common packages
      package:
        name:
          - golang
          - git
          - nodejs
          - neovim
          - tree
          - wget
          - autojump
          - tmux
          - zsh
          - gcc
          - clang
          - g++
          - ripgrep
          - fzf
          - vim
        state: present
      tags: [soy]

    - name: Create folders
      file:
        path: "{{ item | expanduser }}"
        state: directory
        mode: '0755'
      loop:
        - ~/.cache
        - ~/coding
        - ~/.config
      tags: [dotfiles]

    - name: Symlink top-level dotfiles
      file:
        src: "{{ dotfiles_dir }}/{{ item.src }}"
        dest: "{{ home }}/{{ item.dest }}"
        state: link
        force: true
      loop:
        - { src: ".vimrc", dest: ".vimrc" }
        - { src: ".gitconfig", dest: ".gitconfig" }
        - { src: ".tmux.conf", dest: ".tmux.conf" }
        - { src: "_fedora/.zshrc", dest: ".zshrc" }
      tags: [dotfiles]

    - name: Symlink Neovim config
      file:
        src: "{{ dotfiles_dir }}/nvim"
        dest: "{{ home }}/.config/nvim"
        state: link
        force: true
      tags: [nvim, dotfiles]

    - name: Install oh-my-zsh (user mode, non-interactive)
      shell: |
        export RUNZSH=no
        export CHSH=no
        if [ ! -d "$HOME/.oh-my-zsh" ]; then
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        fi
      args:
        executable: /bin/bash
      tags: [zsh]

    # Optional: If you still want to use `updatedb`, include this task.
    - name: Update locate database
      command: updatedb
      tags: [locate]
      when: locate_database_needed | default(false)

    - name: Change default shell to zsh for user Jack
      become: true
      user:
        name: "{{ user }}"
        shell: /bin/zsh
      tags: [zsh]
