[hosts]
centos9-jsonbateman.com  ansible_host=jsonbateman.com ansible_user=root ansible_python_interpreter=/usr/bin/python3
centos10-kbitson.local ansible_host=bitson.local     ansible_user=kbitson ansible_python_interpreter=/usr/bin/python3

[Jsonbateman]
centos9-jsonbateman.com

[KBitson]
centos10-kbitson.local
