[hosts]
centos9-jsonbateman.com  ansible_host=jsonbateman.com ansible_user=root ansible_python_interpreter=/usr/bin/python3
centos10-kbitson.local ansible_host=bitson.local     ansible_user=kbitson ansible_python_interpreter=/usr/bin/python3
centos10-docker ansible_host=127.0.0.1 ansible_port=2222 ansible_user=centos ansible_ssh_private_key_file=~/.ssh/id_ed25519 ansible_python_interpreter=/usr/bin/python3

[jsonbateman]
centos9-jsonbateman.com

[kbitson]
centos10-kbitson.local

[docker]
centos10-docker
