---
- name: Minimal RHEL family server bootstrap
  hosts: hosts # needs to reference inventory.ini
  gather_facts: true
  become: true

  vars:
    # Toggle extras like lazygit via COPR if you want them
    enable_copr_extras: true 
    copr_repos:
      - dejan/lazygit
    base_packages:
      - git
      - curl
      - tmux
      - ripgrep
      - fzf
      - nodejs
      - unzip
      - wget
      - gcc
      - jq
      - gcc-c++
      - make
      - pkgconfig
      - vim
      - neovim

  tasks:
    - name: Ensure EPEL repository is enabled (noop on Fedora)
      ansible.builtin.dnf:
        name: epel-release
        state: present
      when: ansible_facts['distribution'] in ['CentOS Stream', 'RedHat', 'Rocky', 'AlmaLinux']
      tags: [setup]

    - name: Install DNF plugins (for COPR etc.)
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present
      tags: [setup]

    - name: Install base server packages
      ansible.builtin.dnf:
        name: "{{ base_packages }}"
        state: present
      tags: [base]

    - name: (Optional) Enable COPR repos
      ansible.builtin.command: dnf copr enable -y {{ item }}
      loop: "{{ copr_repos }}"
      when: enable_copr_extras | bool
      changed_when: "'enabled' in result.stdout | default('') or result.rc == 0"
      register: result
      tags: [copr]

    - name: (Optional) Install COPR packages
      ansible.builtin.dnf:
        name:
          - lazygit
        state: present
      when: enable_copr_extras | bool
      tags: [copr]

    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      ansible.builtin.file:
        path: /tmp/ansible-made-this.txt
        state: touch
        mode: u=rw,g=r,o=r
      tags: [faff]
